<?php

namespace Arkitecht\LaravelHume\Enums;

enum ChatEventType: string
{
    case SYSTEM_PROMPT = 'SYSTEM_PROMPT';
    case USER_MESSAGE = 'USER_MESSAGE';
    case USER_INTERRUPTION = 'USER_INTERRUPTION';
    case AGENT_MESSAGE = 'AGENT_MESSAGE';
    case FUNCTION_CALL = 'FUNCTION_CALL';
    case FUNCTION_CALL_RESPONSE = 'FUNCTION_CALL_RESPONSE';
    case CHAT_END_MESSAGE = 'CHAT_END_MESSAGE';
    case CHAT_START_MESSAGE = 'CHAT_START_MESSAGE';
    case PAUSE_ONSET = "PAUSE_ONSET";
    case USER_RECORDING_START_MESSAGE = 'USER_RECORDING_START_MESSAGE';
    case RESUME_ONSET = "RESUME_ONSET";
    case ASSISTANT_PROSODY = "ASSISTANT_PROSODY";
}
